---
#
# Ansible managed
#
repository:
  description: Install and configure artifactory on your system.
  homepage: https://robertdebock.nl/
  topics: artifactory, server, development, ansible, molecule, tox, playbook
