---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Try webinterface
      ansible.builtin.uri:
        url: "http://localhost:8081/"
        return_content: true
      register: artifactory_try_webinterface
      failed_when:
        - "'JFrog' not in artifactory_try_webinterface.content"
      retries: 10
      until:
        - artifactory_try_webinterface is succeeded
